import Head from "next/head";
import SignUp from './signup';

export default function Home() {

  return (
    <>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <div className="">
        <SignUp />
      </div>
    </>
    </>
  );
}
